### ISSUE TITLE
Discussing ADO.NET Azure resiliency

### ISSUE THREAD

**Issue by Plasma** [mspnp/azure-guidance#14]
Hello,

When the Azure team suggested elsewhere to use the Topaz library for SQL retries on Azure, there was no clear strategy or example in how to use it (as the library was quite complicated).

I've noticed you have a few examples but they seem to use the very low level retry components (eg using ExecuteReaderWithRetryAsync at https://github.com/mspnp/azure-guidance/blob/master/Retry-Service-Specific.md#examples-sql-database-using-adonet)

This approach seems to be working for me that is similar, thoughts?

````csharp
// 1. Run this one time in your application to set the global retry policy
// Note: I've chosen a fixed interval of 1 second retries for a max of 35 retries to try once per second until 35 seconds have passed
// 30 seconds is the suggested maximum time any reconfiguration/failovers should occur.
// Ideally, the logic was smarter and had shorter delays a few more times up until 30 seconds had elapsed in total.
var fixedInterval = new FixedInterval("Fixed", 35, TimeSpan.FromSeconds(1));
SharedLoggedRetryPolicy = fixedInterval;
 
var retryStrategies = new List<RetryStrategy> { fixedInterval };
var retryManager = new RetryManager(retryStrategies, "Fixed");
 
RetryManager.SetDefault(retryManager);
 
// 2. Always now use a "ReliableSqlConnection" class instance (instead of just SqlConnection) to utilise the retry logic:
var conn = new ReliableSqlConnection(connectionString);
conn.Open();
 
// 3. You're done!
````

**Comment by manikrish** [comment]
This approach looks fine. Just a couple of additional recommendations:
1. While using the ReliableSqlConnection class use the ExecuteCommand overloads on this class to execute the command with retries. 
2.  A fixed interval strategy is not recommended for use with Azure SQL Database. Instead, use an exponential back-off strategy because the service may be overloaded, and longer delays allow more time for it to recover. The current code uses fixed interval retries. There are a couple of recommendations in the resources below.
3. There is no built in async support in the transient fault handling block for ADO.net. There is only synchronous support. The example shows how to implement this for ADO.net with the transient fault handling block. Going async is recommended to ensure threads are not blocked during I/O. You could consider using EF 6 since it has async support with retries.
A couple of resources to look at to get more details:

https://github.com/mspnp/azure-guidance/blob/master/Retry-Service-Specific.md#examples-sql-database-using-adonet – Retry usage guidance for SQLDatabase.
https://msdn.microsoft.com/en-us/library/hh680899(v=pandp.50).aspx
https://msdn.microsoft.com/en-us/data/dn456835.aspx

Do let me know if you have any questions. 

-Mani

**Comment by Plasma** [comment]
Hi @manikrish 

1. Is this necessary? Looking at the decompiled code it seems if I don't use the retry overload, it *should* be using the default retry policy?

2. Do I need to be setting any more "retry policies" apart from the above? I want ReliableSqlConnection to retry connection attempts etc if it can't even open a socket, recently I received this error:

```
[SqlException: Timeout expired. The timeout period elapsed prior to completion of the operation or the server is not responding. This failure occurred while attempting to connect to the routing destination.]
    System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction):94
    System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose):316
    System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady):2559
    System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString):99
    System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds):1390
    System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite):191
    System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite):238
    System.Data.SqlClient.SqlCommand.ExecuteNonQuery():646
    System.Data.SqlClient.SqlCommand.ExecuteNonQuery():496
````

**Comment by Plasma** [comment]
Thanks!

**Comment by manikrish** [comment]
Hi @Plasma 
You are setting the retry policies correctly except that the recommendation is to use exponential backoff as explained earlier. 
 In most cases, one would want the retry mechanism to work if a)The connection failed due to transient errors or b) the query failed due to transient errors. Using the overloads on the ReliableSqlConnection class or the extension methods allow you to do both. You can use specific overloads of ReliableSQLConnection class which do not take the retry policy as an argument using your current approach, in which case the default retry policy is used.
